name: Code Testing and Quality

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Install, Analyze, Test and Build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup mise
      uses: jdx/mise-action@v5
      with:
        install: true
        cache: true

    - name: Install npm packages
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Run formatter
      run: npm run format:check

    - name: Run tests
      run: npm run test:coverage

    - name: Run build
      run: npm run build
