name: Code Testing and Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: airplanegame

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup mise
      uses: jdx/mise-action@v5
      with:
        install: true
        cache: true

    - name: Install npm packages
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Run formatter
      run: npm run format:check

    - name: Run tests
      run: npm run test:coverage

    - name: Run build
      run: npm run build

    - name: Build Docker image
      run: |
        set -a
        . ./versions.env
        set +a
        docker build --build-arg RELEASE_NODE .
